name: Run SafariNowRepoTest

on:
  schedule:
    - cron: '0 6,14,22 * * *'  # Runs at 6 AM, 2 PM, and 10 PM UTC every day
  workflow_dispatch:  # Allows you to trigger manually too

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Run SafariNowRepoTest
      run: mvn clean test -Dtest=SafariNowRepoTest
