name: Run SafariNowRepoTest

on:
  schedule:
    - cron: '0 6,12,18 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y xvfb unzip curl wget gnupg2

    - name: Install Chrome 124 via repo pinning
      run: |
        curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable=124.0.6367.207-1
        google-chrome --version

    - name: Install matching ChromeDriver 124
      run: |
        wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/124.0.6367.207/chromedriver_linux64.zip
        unzip chromedriver.zip
        sudo mv chromedriver /usr/local/bin/
        chromedriver --version

    - name: Set up JDK 22 (Temurin)
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Run SafariNowRepoTest
      run: |
        xvfb-run -a mvn clean test -Dtest=SafariNowRepoTest -DargLine="--enable-preview"
